# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-04 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200304_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goodsType',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
