# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-04 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200304_0203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodstype',
            options={},
        ),
        migrations.AlterModelTable(
            name='goodstype',
            table=None,
        ),
    ]
