# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-26 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20200311_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uphone',
            field=models.CharField(max_length=32, verbose_name='手機號碼'),
        ),
    ]
