# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-26 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20200326_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_id',
            field=models.IntegerField(default=0, verbose_name='第三方用戶id'),
        ),
    ]
