# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-26 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_user_auth_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_id',
        ),
    ]
