# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-28 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_user_auth_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upwd',
            field=models.CharField(max_length=100, verbose_name='密碼'),
        ),
    ]
