# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-23 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccount', models.IntegerField(db_column='ccount')),
            ],
            options={
                'verbose_name_plural': '購物車',
                'verbose_name': '購物車',
                'db_table': 'cart_info',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='商品名稱')),
                ('price', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='商品價格')),
                ('spec', models.CharField(max_length=20, verbose_name='商品規格')),
                ('picture', models.ImageField(null=True, upload_to='static/upload/goods', verbose_name='商品圖片')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否上架')),
            ],
            options={
                'verbose_name_plural': '商品',
                'verbose_name': '商品',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='類型標題')),
                ('picture', models.ImageField(null=True, upload_to='static/upload/goodstype', verbose_name='類型圖片')),
                ('desc', models.TextField(verbose_name='類型描述')),
            ],
            options={
                'verbose_name_plural': '商品類型',
                'verbose_name': '商品類型',
                'db_table': 'goods_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=30, verbose_name='手機號碼')),
                ('upwd', models.CharField(max_length=30, verbose_name='密碼')),
                ('uname', models.CharField(max_length=30, verbose_name='用戶名')),
                ('uemail', models.EmailField(max_length=254, null=True, verbose_name='電子郵件')),
                ('isActive', models.BooleanField(default=False, verbose_name='是否激活')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='goodsType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.GoodsType', verbose_name='商品類型'),
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='cartinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User', verbose_name='客戶'),
        ),
    ]
