# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-25 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uphone',
            field=models.CharField(max_length=32, verbose_name='手機號碼'),
        ),
    ]
