# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-26 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200325_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uphone',
            field=models.CharField(max_length=30, verbose_name='手機號碼'),
        ),
    ]
