# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-04 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200304_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodstype',
            options={'verbose_name': '商品類型', 'verbose_name_plural': '商品類型'},
        ),
        migrations.AlterModelTable(
            name='goodstype',
            table='goods_type',
        ),
    ]
