# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-11 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20200305_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=7, verbose_name='商品價格'),
        ),
    ]
