# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-29 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=30, verbose_name='手機號碼')),
                ('upwd', models.CharField(max_length=30, verbose_name='密碼')),
                ('uname', models.CharField(max_length=30, verbose_name='用戶名')),
                ('uemail', models.EmailField(max_length=254, null=True, verbose_name='電子郵件')),
                ('isActive', models.BooleanField(default=False, verbose_name='是否激活')),
            ],
        ),
    ]
