# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-05 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20200304_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Goods', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='客戶')),
            ],
            options={
                'db_table': 'cart_info',
                'verbose_name_plural': '購物車',
                'verbose_name': '購物車',
            },
        ),
    ]
